package cz.siret.prank.geom

import groovy.transform.CompileStatic
import groovy.util.logging.Slf4j
import org.openscience.cdk.geometry.surface.NumericalSurface
import org.openscience.cdk.interfaces.IAtom
import org.openscience.cdk.interfaces.IAtomContainer
import org.openscience.cdk.silent.Atom
import org.openscience.cdk.silent.AtomContainer

/**
 * Wraps CDK's {@link NumericalSurface} with a fallback for elements whose
 * VdW radius is {@code null} in CDK's {@code Elements} enum.
 *
 * <p>Without the wrap, {@code PeriodicTable.getVdwRadius("Co")} (and others) returns
 * {@code null} and {@code NumericalSurface.init()} throws NPE on cobalamin / nickel-enzyme
 * / cupric structures whenever those metal atoms are part of the protein surface input
 * (e.g. via the {@code -cofactors} feature).
 *
 * <p>The wrap substitutes affected atoms with a proxy element (Krypton, CDK enum VdW
 * 2.02 A) before calling {@code NumericalSurface}. The proxy is close to the actual
 * radii of the common biological metals (Co/Ni/Cu/Rh/Os/Ir all ~2.0 A in CDK's own
 * {@code radii-vdw.txt}). For radioactive / synthetic elements the same proxy is used;
 * those don't occur in real PDB structures.
 *
 * <p>The patched container is internal; original atoms are unaffected.
 *
 * <p>This workaround stays out of CDK itself - see {@code local/cdk-vdw-radius-gap.md}
 * for the upstream-bug write-up.
 *
 * @see cz.cuni.cusbg.surface.FasterNumericalSurface for the parallel fork-based fix
 *      applied to the optimised surface implementation.
 */
@Slf4j
@CompileStatic
class PatchedCdkNumericalSurface {

    /**
     * Elements whose {@code rW} field in {@code org.openscience.cdk.config.Elements}
     * (CDK 2.12) is hard-coded as {@code null}. Generated by scanning the enum.
     *
     * Biologically common: Co, Ni, Cu, Rh, Os, Ir.
     * The rest are radioactive / synthetic and shouldn't appear in PDB structures.
     */
    static final Set<String> NULL_VDW_SYMBOLS = ([
            "Co", "Ni", "Cu", "Rh", "Os", "Ir",
            "Po", "At", "Rn", "Fr", "Ra",
            "Ac", "Pa", "Np", "Pu", "Am", "Cm", "Bk", "Cf", "Es", "Fm", "Md", "No", "Lr",
            "Rf", "Db", "Sg", "Bh", "Hs", "Mt", "Ds", "Rg", "Cn", "Nh", "Fl", "Mc", "Lv", "Ts", "Og",
            "Uut", "Uup", "Uus", "Uuo"
    ] as Set<String>).asImmutable() as Set<String>

    /**
     * Proxy element: Krypton has VdW = 2.02 A in CDK's enum, within 0.05 A of
     * the actual radii of all biological null-VdW elements per CDK's
     * {@code radii-vdw.txt} (Co/Ni/Cu/Rh/Os/Ir = 2.0 A).
     */
    static final String PROXY_SYMBOL = "Kr"

    private final NumericalSurface delegate

    PatchedCdkNumericalSurface(IAtomContainer container, double solventRadius, int tesslevel) {
        this.delegate = new NumericalSurface(patchedContainer(container), solventRadius, tesslevel)
    }

    double getTotalSurfaceArea() {
        return delegate.totalSurfaceArea
    }

    javax.vecmath.Point3d[] getAllSurfacePoints() {
        return delegate.allSurfacePoints
    }

    /**
     * Build a copy of {@code original} with affected atoms swapped for a proxy element
     * that has a sane VdW radius in CDK's enum. The copy shares 3D coordinates with the
     * original; only the symbol is substituted.
     */
    private static IAtomContainer patchedContainer(IAtomContainer original) {
        int n = original.atomCount
        AtomContainer copy = new AtomContainer(n, 0, 0, 0)
        IAtom[] patched = new IAtom[n]
        int substitutions = 0
        for (int i = 0; i < n; i++) {
            IAtom a = original.getAtom(i)
            String sym = a.symbol
            if (NULL_VDW_SYMBOLS.contains(sym)) {
                patched[i] = new Atom(PROXY_SYMBOL, a.point3d)
                substitutions++
            } else {
                patched[i] = a
            }
        }
        if (substitutions > 0) {
            log.debug "PatchedCdkNumericalSurface: substituted {} atoms with proxy symbol {} (null-VdW workaround)",
                    substitutions, PROXY_SYMBOL
        }
        copy.setAtoms(patched)
        return copy
    }
}
